version: "3.8"

services:
  tasksql:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tsmuser
      - POSTGRES_PASSWORD=tsmpassword
      - POSTGRES_DB=tsmdb